blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/devmoath/jira-laravel/discussions/new?category=q-a
      about: Ask the community for help
    - name: Request a feature
      url: https://github.com/devmoath/jira-laravel/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Report a security issue
      url: https://github.com/devmoath/jira-laravel#security-vulnerabilities
      about: Learn how to notify us for sensitive bugs
