name: Formats

on: ["push", "pull_request"]

jobs:
    formats:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.2]
                stability: [prefer-lowest, prefer-stable]

        name: Formats php${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.stability }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --${{ matrix.stability }} --no-interaction

            - name: Coding Style Checks
              run: composer test:lint

            - name: Refactor Checks
              run: composer test:refactor

            - name: Type Checks
              run: composer test:types
